news_sites:
        eluniversal:
          url: http://www.eluniversal.com.mx
          queries:
            homepage_article_links: '.field-content a'
            article_body: '.field-name-body p'
            article_title: '.pane-content h1'
            article_author: '.field-name-title .field-items div'
            article_date: '.pane-content .fechap'
            article_location: '.pane-conten div'
        eltiempo:
          url: https://eltiempo.com
          queries:
            homepage_article_links: '.title-container a'
            article_body: '.contenido'
            article_title: '.titulo'
            article_author: '.autor span'
            article_date: '.fecha'
            article_location: '.tags-en-articulo-tag a'
        lemonde:
          url: https://www.lemonde.fr
          queries:
            homepage_article_links: '.article a'
            article_body: '.article__content p'
            article_title: '.article__heading h1'
            article_author: '.meta__author a'
            article_date: '.meta__date'
            article_location: '.breadcrumb__child a'
        lexpress:
          url: https://l-express.ca/categorie/toronto/
          queries:
            homepage_article_links: '.card-section-support-standard a'
            article_body: '.article-content p'
            article_title: '.article-header h1'
            article_author: '.article-author-details a'
            article_date: '.article-author-details'
            article_location: 'toronto'

            
      